### ISSUE TITLE
what is the meaning of "data" in the json file?

### ISSUE THREAD

**Issue by gdshen** [DeepSystems/supervisely-project-example#1]
How to decode strings like 

"eJzrDPBz5+WS4mJgYOD19HAJYmBgmsHAwHiHkRko4nHPIxdIsQX4hLgC6f///y+9Of8ukMVYEuQXzODw7EYaUP0KTxfHkIo5b+8aFi02kGhLrIxZ8oRpXmjfRtn2W3aPWKrVdu1t270lx/3gglgDCeEj6wT3GwVV7D908s+C43xMN8NyArJ09a9tW81tK3zozFobqVNblq5ZGWyUevJeDtOMUobNXAlx18Xnd3WcKarduFLJqNv1q8m93o+S3Hbnz7xbdr5Q+lSMiL6a1+YfLJ/vzFhY9U0q2nn23C0dyy3NJht9XjnT+4vRWZNrnTO/5T3Lu/y4c2l2mOZXrSQ+f2dn4+T6nSf73W/+/DTnZol9zdk/216e2z71/TJZ7XNffLf8/ft9+/bt013Xr52Z+ix31s9Tk2/+aY5ZVnXqzrQLz473rZhWvvn2G7F3prW3dl9KstqtERSsnuQ1sZ9ZWA0InoWbZJ+peyQh/Jljme/ZM4aGj023Klj6ST37lKbmqZZsNmNGkKaQ4foZmzT58rJ8NobMaDeJ9vE5o3E2L070c0Nab6dm+rMZTQeP9Nw2eZTWqZnTNXkG5wxTkMGMPt2dmlMMfu852HPH5+nXGtkHtTJqaWeW+R7xSa1OOrVsynzv40eOiBga+xw8Ub+PTxgEiqu1zjjPAobkwSNHeq5M+ZNWarH56BEg+5yItaaMmtqyBBb/Gx0368WVOY2nvu0EgZ9PfX9+l52BAX6fCXl2Lchwq8nMCz9fTzJw/iIIdFPhmZBju5pnS6pBwLP/QUlJSceyus7Xsxnsfn06AcgOYzfjPnPj7LrbS88G3XmzfpdWjlZlccWMSf+fa03dYznp1Zb7WdXPVy37YSthG5p3nSmsf9lNvnPbbyqbqdSLrZmWu18zVGe1tFqo7LMoo/Dfp/vn37+fPvXWR/V1x3Zevn+2UHfzyZDNeVlT845t2rY5TtAoO/9T4v6M9K/Bgge+qC9nLunfaLI7WvMzv8Qz65xPqYxLgQmYwdPVz2WdU0ITAH7zch0="? 

Is it a base64 encoded image?

**Comment by TDionis** [comment]
It is. Check out this python example: https://docs.supervise.ly/ann_format/#bitmap

**Comment by gdshen** [comment]
Thanks, the documentations make it clear.😄
